#!/bin/bash

# Supabase Incident Finder - Helps you quickly identify production incidents
# This script provides URLs and commands to find incidents for manual labeling

echo "╔══════════════════════════════════════════════════════════════════════╗"
echo "║          Supabase Incident Finder - Manual Labeling Helper          ║"
echo "╚══════════════════════════════════════════════════════════════════════╝"
echo ""
echo "This script will help you find ~15 Supabase production incidents"
echo "Estimated time: 1-2 hours for manual labeling"
echo ""

# Create output file
OUTPUT_CSV="/Users/rohankatakam/Documents/brain/coderisk/supabase_incidents.csv"

echo "Creating CSV template at: $OUTPUT_CSV"
cat > "$OUTPUT_CSV" << 'EOF'
pr_number,type,date,file_changed,description
39866,revert,2024-10-25,studio/components/table-editor/TableEditor.tsx,Table editor regression - original incident
EOF

echo "✓ Template created with one example"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 1: Find Revert PRs (Easiest - These are confirmed incidents)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Open these URLs in your browser:"
echo ""
echo "1. Recent revert PRs:"
echo "   https://github.com/supabase/supabase/pulls?q=is%3Apr+revert+in%3Atitle+is%3Aclosed+sort%3Aupdated-desc"
echo ""
echo "2. Hotfix PRs:"
echo "   https://github.com/supabase/supabase/pulls?q=is%3Apr+hotfix+in%3Atitle+is%3Aclosed+sort%3Aupdated-desc"
echo ""
echo "3. Critical bug fixes:"
echo "   https://github.com/supabase/supabase/pulls?q=is%3Apr+critical+bug+is%3Aclosed+sort%3Aupdated-desc"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 2: For Each PR You Find"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Collect this information (5 min per incident):"
echo ""
echo "  1. PR Number (e.g., 39866)"
echo "  2. Type (revert/hotfix/critical-bug)"
echo "  3. Date merged (e.g., 2024-10-25)"
echo "  4. Main file changed - look in 'Files changed' tab"
echo "     Pick the PRIMARY file (usually 1-2 files are the root cause)"
echo "  5. One-sentence description"
echo ""
echo "Add each to: $OUTPUT_CSV"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "EXAMPLE: How to Extract Data from a PR"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Let's say you open: https://github.com/supabase/supabase/pull/39866"
echo ""
echo "You see:"
echo "  • Title: 'fix: revert 39818'"
echo "  • Merged: Oct 25, 2024"
echo "  • Files changed (1):"
echo "    - studio/components/table-editor/TableEditor.tsx"
echo "  • Description: Reverting PR that broke table editor"
echo ""
echo "You add to CSV:"
echo "39866,revert,2024-10-25,studio/components/table-editor/TableEditor.tsx,Table editor regression"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "GOAL: Find 15 Incidents"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Target: 15 incidents (1-2 hours of manual work)"
echo "This is enough for a compelling demo with statistical validity"
echo ""
echo "Time breakdown:"
echo "  • 5 min per incident × 15 incidents = 75 minutes"
echo "  • Buffer for searching/validation: +30 minutes"
echo "  • Total: ~2 hours"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "AFTER YOU LABEL 15 INCIDENTS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run the automated scoring:"
echo ""
echo "  bash /Users/rohankatakam/Documents/brain/coderisk/score_supabase_incidents.sh"
echo ""
echo "This will:"
echo "  1. Ingest Supabase repo (30 min, one-time)"
echo "  2. Score your 15 labeled incidents (20 min)"
echo "  3. Score 50 random safe commits (30 min)"
echo "  4. Generate Money Slide graph (2 min)"
echo ""
echo "Total automated time: ~1.5 hours (runs unattended)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "QUICK START"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Open the URLs above in your browser"
echo "2. Open $OUTPUT_CSV in Excel/Google Sheets"
echo "3. Add one row per incident (5 min each)"
echo "4. When you have 15, run: bash score_supabase_incidents.sh"
echo ""
echo "Good luck! 🚀"
echo ""
