-- Migration 009: Add idempotency tracking timestamps
-- Purpose: Enable incremental processing and resume capability for all microservices
-- Author: Claude (Idempotency Implementation)
-- Date: 2025-11-18

-- ============================================================================
-- Add atomization tracking to github_commits
-- ============================================================================

-- Track when a commit was atomized into code blocks
ALTER TABLE github_commits
ADD COLUMN IF NOT EXISTS atomized_at TIMESTAMP WITHOUT TIME ZONE;

-- Index for efficient filtering of unprocessed commits
CREATE INDEX IF NOT EXISTS idx_commits_atomized
ON github_commits(repo_id, topological_index)
WHERE atomized_at IS NULL;

COMMENT ON COLUMN github_commits.atomized_at IS
'Timestamp when commit was processed by crisk-atomize to create/update code blocks';

-- ============================================================================
-- Add indexing tracking to code_blocks
-- ============================================================================

-- Track when temporal/incident analysis was performed
ALTER TABLE code_blocks
ADD COLUMN IF NOT EXISTS temporal_indexed_at TIMESTAMP WITHOUT TIME ZONE;

-- Track when ownership analysis was calculated
ALTER TABLE code_blocks
ADD COLUMN IF NOT EXISTS ownership_indexed_at TIMESTAMP WITHOUT TIME ZONE;

-- Track when coupling analysis was calculated
ALTER TABLE code_blocks
ADD COLUMN IF NOT EXISTS coupling_indexed_at TIMESTAMP WITHOUT TIME ZONE;

-- Indexes for efficient filtering of blocks needing reprocessing
CREATE INDEX IF NOT EXISTS idx_code_blocks_temporal_stale
ON code_blocks(repo_id, incident_count)
WHERE temporal_indexed_at IS NULL OR (incident_count > 0 AND temporal_indexed_at < last_incident_date);

CREATE INDEX IF NOT EXISTS idx_code_blocks_ownership_stale
ON code_blocks(repo_id)
WHERE ownership_indexed_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_code_blocks_coupling_stale
ON code_blocks(repo_id)
WHERE coupling_indexed_at IS NULL;

-- Add comments for documentation
COMMENT ON COLUMN code_blocks.temporal_indexed_at IS
'Timestamp when temporal/incident summary was generated by crisk-index-incident';

COMMENT ON COLUMN code_blocks.ownership_indexed_at IS
'Timestamp when ownership metrics (original_author, last_modifier, familiarity_map) were calculated by crisk-index-ownership';

COMMENT ON COLUMN code_blocks.coupling_indexed_at IS
'Timestamp when co-change coupling analysis was performed by crisk-index-coupling';

-- ============================================================================
-- Migration complete
-- ============================================================================

DO $$
BEGIN
    RAISE NOTICE 'Migration 009 complete: Added idempotency tracking timestamps';
    RAISE NOTICE '  - github_commits.atomized_at for crisk-atomize';
    RAISE NOTICE '  - code_blocks.temporal_indexed_at for crisk-index-incident';
    RAISE NOTICE '  - code_blocks.ownership_indexed_at for crisk-index-ownership';
    RAISE NOTICE '  - code_blocks.coupling_indexed_at for crisk-index-coupling';
    RAISE NOTICE '  - Created 4 indexes for efficient incremental processing';
END $$;
