[project]
name = "workshops"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "baml>=0.19.1",
    "jupyter>=1.1.1",
    "nbformat>=5.10.4",
    "pyyaml>=6.0.2",
]
